title: Warranty Wise
author: Jiawen Chen & Derek Nishimura
show_downloads: false
remote_theme: daattali/beautiful-jekyll@6.0.1
github:
  is_project_page: true
  repository_url: https://github.com/warranty-wise/warranty-wise.github.io
navbar-links:
  Github: https://github.com/warranty-wise/warranty-wise